include: package:flutter_lints/analysis_options.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - always_specify_types
    - public_member_api_docs: false
